### ISSUE TITLE
[Errno 2] No such file or directory  - processing perfdata

### ISSUE THREAD

**Issue by NeySlim** [shawn-sterling/graphios#98]
Graphios works well then this error is showing up:

December 16 16:09:45 graphios.py CRITICAL couldn't remove file /omd/sites/prod/var/pnp4nagios/spool/service-perfdata.1450278571 error:[Errno 2] No such file or directory: '/omd/sites/prod/var/pnp4nagios/spool/service-perfdata.1450278571'
couldn't remove file /omd/sites/prod/var/pnp4nagios/spool/service-perfdata.1450278571 error:[Errno 2] No such file or directory: '/omd/sites/prod/var/pnp4nagios/spool/service-perfdata.1450278571'
Traceback (most recent call last):

  File "/usr/local/bin/graphios.py", line 567, in module
    main()
  File "/usr/local/bin/graphios.py", line 546, in main
    process_spool_dir(spool_directory)
  File "/usr/local/bin/graphios.py", line 444, in process_spool_dir
    if check_skip_file(perfdata_file, file_dir):
  File "/usr/local/bin/graphios.py", line 476, in check_skip_file
    if os.stat(file_dir)[6] == 0:

OSError: [Errno 2] No such file or directory: '/omd/sites/prod/var/pnp4nagios/spool/host-perfdata.1450278571'

After this error, graphios hangs, no perfdata is processed.

**Comment by NeySlim** [comment]
Given pnp4nagios spool instead of grpahios spool ...
